package gsb_hibernate;
// Generated 2 févr. 2020 16:21:32 by Hibernate Tools 5.4.3.Final

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String prenom;
	private String fonction;

	public Utilisateur() {
	}

	public Utilisateur(String nom, String prenom, String fonction) {
		this.nom = nom;
		this.prenom = prenom;
		this.fonction = fonction;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

}
